### ISSUE TITLE
P2P Code Review

### ISSUE THREAD

**Issue by lorenzoworx** [preciousbetine/microverse-awesome-books#2]
Hi @preciousbetine. Great job completing this task
 ![thumbs-up-gif](https://tenor.com/view/ok-all-nice-gif-22927671.gif)
Although I would suggest you add some validation to the form and ensure the input fields are filled before generating a book entry.

**Comment by preciousuwhubetine** [comment]
This issue has been fixed. Thanks for pointing it out!
